global_frame: odom
rolling_window: true

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}

# Burger
# local_costmap:
#   global_frame: odom
#   # robot_base_frame: base_footprint
#
#   # update_frequency: 10.0
#   # publish_frequency: 10.0
#   # transform_tolerance: 0.5
#
#   # static_map: false
#   rolling_window: true
#   width: 10
#   height: 10
#   # resolution: 0.05
#
#   plugins:
#     - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
#     - {name: inflation,                 type: "costmap_2d::InflationLayer"}
