# Husky costmap
# footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
# footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 5.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6

robot_radius: 0.01

static_map: false



#layer definitions
# static:
#     map_topic: /map
#     subscribe_to_updates: true

obstacles_laser:
   enabled: true
   inflation_radius: 0.07
   track_unknown_space: false
   combination_method: 1
   observation_sources: laser
   laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    enabled:              true
    cost_scaling_factor:  10.0
    inflation_radius: 0.3

# Burger costmap
# obstacle_range: 5
# raytrace_range: 5.5
#
# robot_base_frame: base_link
# update_frequency: 4.0
# publish_frequency: 3.0
# transform_tolerance: 0.5
#
# resolution: 0.05
#
footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
robot_radius: 0.105
#
# # inflation_radius: 0.5
# cost_scaling_factor: 3.0
#
# # map_type: costmap
# # observation_sources: scan
# # scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}
#
# static:
#     map_topic: /map
#     subscribe_to_updates: true
#
# obstacles_laser:
#     observation_sources: laser
#     laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}
#
# inflation:
#     inflation_radius: 0.3
